pipeline:
  frontend:
    image: node:8.2.1
    commands:
      - npm install
      - npm test

  publish:
    image: plugins/docker
    repo: ycliuhw/k8s-testing-app
    secrets: [ docker_username, docker_password ]
    auto_tag: true
    # auto_tag_suffix: k8s
    dockerfile: Dockerfile
