apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: ingress-k8s-testing-app
  namespace: k8s-testing-app
spec:
  rules:
  - host: a2c698709faa011e79b44062cd273c43-384509168.ap-southeast-2.elb.amazonaws.com
    http:
      paths:
      - backend:
          serviceName: k8s-testing-app-javascript
          servicePort: 3000
        path: /fe-search
